# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator


install autoconf
install automake
install curlftpfs
install ffmpeg
install gdbm
install gettext
install glib
install lame
install libffi
install libtool
install libvo-aacenc
install mongodb
install node
install openssl
install pkg-config
install python
install readline
install sqlite
install ssh-copy-id
install unrar
install wget
install x264
install xvid
